diff --git a/extensions/browser/extension_function_histogram_value.h b/extensions/browser/extension_function_histogram_value.h
index 8d3b969f8965b..1dff8a0ed8252 100644
--- a/extensions/browser/extension_function_histogram_value.h
+++ b/extensions/browser/extension_function_histogram_value.h
@@ -2022,6 +2022,33 @@ enum HistogramValue {
   AUTOFILLPRIVATE_GETREQUIREDATTRIBUTETYPESFORENTITYTYPENAME = 1959,
   PDFVIEWERPRIVATE_GLICSUMMARIZE = 1960,
   GLICPRIVATE_GETSTATE = 1961,
+  // BrowserOS: extension function histogram values
+  DELETED_BROWSER_OS_GETACCESSIBILITYTREE = 1962,
+  DELETED_BROWSER_OS_GETINTERACTIVESNAPSHOT = 1963,
+  DELETED_BROWSER_OS_CLICK = 1964,
+  DELETED_BROWSER_OS_INPUTTEXT = 1965,
+  DELETED_BROWSER_OS_CLEAR = 1966,
+  DELETED_BROWSER_OS_GETPAGELOADSTATUS = 1967,
+  DELETED_BROWSER_OS_SCROLLUP = 1968,
+  DELETED_BROWSER_OS_SCROLLDOWN = 1969,
+  DELETED_BROWSER_OS_SCROLLTONODE = 1970,
+  DELETED_BROWSER_OS_SENDKEYS = 1971,
+  DELETED_BROWSER_OS_GETPAGESTRUCTURE = 1972,
+  DELETED_BROWSER_OS_CAPTURESCREENSHOT = 1973,
+  DELETED_BROWSER_OS_GETSNAPSHOT = 1974,
+  BROWSER_OS_GETPREF = 1975,
+  BROWSER_OS_SETPREF = 1976,
+  DELETED_BROWSER_OS_GETALLPREFS = 1977,
+  BROWSER_OS_LOGMETRIC = 1978,
+  BROWSER_OS_GETVERSIONNUMBER = 1979,
+  DELETED_BROWSER_OS_EXECUTEJAVASCRIPT = 1980,
+  DELETED_BROWSER_OS_CLICKCOORDINATES = 1981,
+  DELETED_BROWSER_OS_TYPEATCOORDINATES = 1982,
+  SIDEPANEL_BROWSEROSTOGGLE = 1983,
+  SIDEPANEL_BROWSEROSISOPEN = 1984,
+  BROWSER_OS_GETBROWSEROSVERSIONNUMBER = 1985,
+  BROWSER_OS_CHOOSEPATH = 1986,
+  BROWSER_OS_SHOWTOAST = 1987,
   // Last entry: Add new entries above, then run:
   // tools/metrics/histograms/update_extension_histograms.py
   ENUM_BOUNDARY
